---
# tasks file for opercoder.test

- name: Ensure necessary packages are installed
  apt:
    pkg: ['python3-pip', 'curl']
    state: present
    update_cache: true
  tags:
    - packages

- name: Ensure groups are present
  group:
    name: "{{ item }}"
    state: present
  loop:
    - devops
    - developers
  tags:
    - groups

- name: Manage users
  include_tasks: manage_users.yml
  tags:
    - users

- name: Manage sudoers
  include_tasks: sudo_users.yml
  tags:
    - sudoers

- name: Disable users
  include_tasks: disable_users.yml
  tags:
    - disable
