---
#dependency:
#  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: mipguerrero26/ubuntu-python3
    pre_build_image: true
#    command: /usr/sbin/init
#    options:
#      hostname: molecule
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
