---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-ubuntu22.04
    image: mipguerrero26/ubuntu-python3
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
